# travis config, based on https://github.com/craigcitro/r-travis

language: r
sudo: false
cache:
  directories: $HOME/travis/open-mpi
  packages: true

r:
  - oldrel
  - release
  - devel

r_github_packages:
  - jimhester/covr
  - rstats-db/RSQLite

before_install:
  - sh ./travis/install-mpi.sh $HOME/travis

after_success:
  - Rscript -e 'library(covr); coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
