# travis config, based on https://github.com/craigcitro/r-travis

language: r
sudo: false
cache:
  directories:
    - $HOME/travis/open-mpi
    - $HOME/R/Library

env:
  - R_LIB_USER=$HOME/R/Library TRAVIS_ROOT=$HOME/travis

r:
  - oldrel
  - release
  - devel

r_github_packages:
  - jimhester/covr
  - rstats-db/RSQLite

before_install:
  - mkdir $TRAVIS_ROOT
  - sh ./travis/install-mpi.sh $TRAVIS_ROOT

after_success:
  - Rscript -e 'library(covr); coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
